import { api } from "~/utils/api";
import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import CreateParking from "./components/CreateParking";
import { DashboardWrapper } from "~/components/DashboardWrapper/DashboardWrapper";
import { useUser } from "@clerk/nextjs";

const CreateParkingPage: NextPage<{ username: string }> = ({ username }) => {
  const { user, isLoaded, isSignedIn } = useUser();
  const profile =
    isLoaded && user?.id
      ? api.profile.getProfileById.useQuery({
          id: user.id,
        })
      : undefined;
  return (
    <>
      <Head>
        <title>Parky | Easy parking everywhere</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardWrapper active="myparkingspots">
          <CreateParking />
        </DashboardWrapper>
      </main>
    </>
  );
};

export default CreateParkingPage;
