import { useUser } from "@clerk/nextjs"
import styles from "./index.module.scss"
import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { DashboardWrapper } from "~/components/DashboardWrapper/DashboardWrapper"
import { UiBox } from "~/components/uiBox/uiBox"
import { api } from "~/utils/api"

const Login: NextPage = () => {
  const router = useRouter()
  const { user, isLoaded, isSignedIn } = useUser()
  if (!isLoaded) {
    return (
      <>
        <Head>
          <title>My parking spots | Parky</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <DashboardWrapper active="myparkingspots">
            <div>Loading data...</div>
          </DashboardWrapper>
        </main>
      </>
    )
  }
  if (isLoaded && !isSignedIn) {
    void router.push("/")
    return <></>
  }
  const { data, error } = api.parking.getParkingsByUserId.useQuery({
    userId: user.id,
  })
  return (
    <>
      <Head>
        <title>Login | Parky</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardWrapper active="myparkingspots">
          <div>
            <h2>My parking spots</h2>
            <UiBox className={styles.bookingListWrapper}>
              <div className={styles.bookingListHeader}>
                <p>Address</p>
                <p>price</p>
                <p>Details</p>
              </div>
              <ul></ul>
            </UiBox>
          </div>
        </DashboardWrapper>
      </main>
    </>
  )
}
export default Login
