import type { NextPage } from "next"
import Head from "next/head"
import { DashboardWrapper } from "~/components/DashboardWrapper/DashboardWrapper"
import { UiBox } from "~/components/uiBox/uiBox"

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login | Parky</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardWrapper active="myparkingspots">
          <UiBox>
            <div></div>
          </UiBox>
        </DashboardWrapper>
      </main>
    </>
  )
}

export default Login
