import { Footer } from "~/components/Footer/Footer";
import { PageHeader } from "~/components/pageHeader/pageHeader";
import { type NextPage } from "next";
import { WorkInProgress } from "~/components/WorkInProgress/WorkInProgress";
import styles from "./index.module.scss";
import Head from "next/head";
const Help: NextPage = () => {
  return (
    <>
      <Head>
        <title>Help | Parky</title>
        <meta name="Help page" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <PageHeader secondaryMenu={false} active="help">
        <div className={styles.wrapper}>
          <main>
            <WorkInProgress></WorkInProgress>
          </main>
          <Footer />
        </div>
      </PageHeader>
    </>
  );
};

export default Help;
