import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const CreateProfile: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create profile | Parky</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
            </main>
        </>
    );
};

export default CreateProfile; 
