import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import CreateProfile from "~/components/CreateProfile/CreateProfile";

const CreateProfilePage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create profile | Parky</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <CreateProfile />
            </main>
        </>
    );
};

export default CreateProfilePage; 
