import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { InputField } from "~/components/InputField/InputField";

const CreateProfile: NextPage = () => {
    const [username, setUsername] = useState("")
    return (
        <>
            <Head>
                <title>Create profile | Parky</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                <InputField inputType="text" name="username" label="Username" placeholder="Username" value={username} onChange={setUsername} />
                </div>
            </main>
        </>
    );
};

export default CreateProfile; 
