import { useUser } from "@clerk/nextjs"
import styles from "./index.module.css"
import { type NextPage } from "next"
import Head from "next/head"
import CreateProfile from "~/components/CreateProfile/CreateProfile"
import { api } from "~/utils/api"
import Link from "next/link"

const CreateProfilePage: NextPage = () => {
  const { user, isSignedIn, isLoaded } = useUser()
  const profile = user
    ? api.profile.getProfileById.useQuery({ id: user.id })
    : undefined
  if (!isLoaded) {
    return <div>Loading...</div>
  }
  if (isSignedIn && !profile) {
    return (
      <>
        <Head>
          <title>Create profile | Parky</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <CreateProfile />
        </main>
      </>
    )
  }

  if (profile) {
    return (
      <div>
        <h1>You already have a profile at Parky</h1>
        <Link href={"/"}>Go back home</Link>
      </div>
    )
  }
  return (
    <div>
      <h1>You need to create an account first</h1>
      <Link href={"/"}>Go back home</Link>
    </div>
  )
}
export default CreateProfilePage
