import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useState } from "react";

const Home: NextPage = () => {
    const { mutate } = api.profile.create.useMutation()
    const profiles = api.profile.getAll.useQuery()
    const user = useUser()
    return (
        <>
            <Head>
                <title>Parky | Easy parking everywhere</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {!user.isSignedIn &&
                    <SignInButton></SignInButton>
                }
                {!!user.isSignedIn && <>
                    <SignOutButton></SignOutButton>
                </>
                }
                <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

            </main >
        </>
    );
};

export default Home;
