import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.scss";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useEffect, useState } from "react";
import { PageHeader } from "~/components/pageHeader/pageHeader";
import { UiBox } from "~/components/uiBox/uiBox";
import { Accordion } from "~/components/Accordion/Accordion";

const Home: NextPage = () => {
  const { mutate } = api.profile.create.useMutation();
  const profiles = api.profile.getAll.useQuery();
  // const { data: test, error, isLoading } = api.parking.getAll.useQuery();
  const user = useUser();

  // useEffect(() => {
  //   console.log(test);
  // }, [isLoading]);

  // arrows

  return (
    <>
      <Head>
        <title>Parky | Easy parking everywhere</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader secondaryMenu={false} secondaryMenuContents={null}>
        <div>
          <section className={styles.hero}>
            <div>
              <UiBox>
                <h3>Book a parking spot</h3>
              </UiBox>
            </div>
            <span>OR</span>
            <div>
              <UiBox>
                <h3>Register as an owner</h3>
              </UiBox>
            </div>
          </section>
          <section className={styles.explainer}>
            <h1 className={styles.headerBlue}>What is Parky?</h1>
            <div className={styles.explainerWrapper}>
              <article>
                <span>1</span>
                <div>
                  <h3>Register an account</h3>
                  <p>
                    Parky can be accessed with your account, providing security
                    for both drivers and owners.
                  </p>
                </div>
              </article>
              <article>
                <span>2</span>
                <div>
                  <h3>Top up your account</h3>
                  <p>
                    Payments are handled through ParkCoin - a platform currency
                    which can be exchanged for parking spots and other benefits.
                  </p>
                </div>
              </article>
              <article>
                <span>
                  <div></div>3 <div></div>
                </span>
                <div>
                  <h3>Find the desired location</h3>
                  <p>
                    Parky map consists of rentable private parking spots
                    provided by other users of the platform.
                  </p>
                </div>
              </article>
              <article>
                <span>4</span>
                <div>
                  <h3>Book it</h3>
                  <p>
                    Booking process is quick and seamless, just adjust the
                    duration and date to proceed.
                  </p>
                </div>
              </article>
              <article>
                <span>5</span>
                <div>
                  <h3>Park in your spot</h3>
                  <p>
                    You are provided with a 15 minute window before and after if
                    your commute took longer than expected.
                  </p>
                </div>
              </article>
            </div>
          </section>
          {/* features */}
          <section className={styles.features}>
            <UiBox>
              <div></div>
              <h3>Save fuel</h3>
            </UiBox>
            <UiBox>
              <div></div>
              <h3>Drive sustainably</h3>
            </UiBox>
            <UiBox>
              <div></div>
              <h3>Quick booking</h3>
            </UiBox>
            <UiBox>
              <div></div>
              <h3>Get benefits</h3>
            </UiBox>
          </section>
          <section className={styles.faq}>
            <div>SOME IMAGE</div>
            <Accordion />
          </section>
          {/* old sign in component */}
          <main className={styles.main}>
            {!user.isSignedIn && <SignInButton></SignInButton>}
            {!!user.isSignedIn && (
              <>
                <SignOutButton></SignOutButton>
              </>
            )}
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          </main>
        </div>
      </PageHeader>
    </>
  );
};

export default Home;
