import { useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import type { NextPage } from "next";
import Head from "next/head";

const Login: NextPage = () => {
    const user = useUser()
    if (!user.isLoaded) {
        return <div>Loading</div>
    }
    if (user.isSignedIn) {
        return <div>User is already signed in</div>
    }
        return (
            <>
                <Head>
                    <title>Login | Parky</title>
                    <meta name="description" content="Generated by create-t3-app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className={styles.main}>
                </main>
            </>
        )
};

export default Login
