import styles from "./index.module.scss";
import { type NextPage } from "next";
import Head from "next/head";

const Signup: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sign up | Parky</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
    </>
  );
};

export default Signup;
