import { SignIn, useUser } from "@clerk/nextjs"
import styles from "./index.module.scss"
import type { NextPage } from "next"
import Head from "next/head"
import { RouterInputs, api } from "~/utils/api"
import { InputField } from "~/components/FormElements/InputField/InputField"
import { type SubmitHandler, useForm } from "react-hook-form"
import { toast } from "react-hot-toast"

const Test: NextPage = () => {
  const user = useUser()
  const {} = api.parkingReview.getAllById.useQuery({
    parkingId: "clhunjals0000uw5q1jbwuly8",
  })
  const { mutate: addCoin } = api.coin.addCoin.useMutation({
    onSuccess: () => {
      toast.success("transaction complete")
    },
    onError: () => {
      toast.error("something went wrong")
    },
  })
  const { register, handleSubmit } = useForm<RouterInputs["coin"]["addCoin"]>()

  const onSubmit: SubmitHandler<RouterInputs["coin"]["addCoin"]> = (data) => {
    if (user.user) {
      addCoin({ ...data, toAccountId: user.user.id })
    }
  }
  if (!user.isLoaded) {
    return <div>Loading</div>
  }

  return (
    <>
      <Head>
        <title>Login | Parky</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*eslint-disable-next-line */}
        <form onSubmit={handleSubmit(onSubmit)}>
          <InputField
            register={register}
            name="amount"
            label="Purchase amount"
            inputType="number"
            placeholder=""
          />
          <input type="submit" />
        </form>
      </main>
    </>
  )
}

export default Test
